# Generated by Django 2.0 on 2018-11-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181031_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readed',
            field=models.IntegerField(default=0),
        ),
    ]
